cmd_/home/intel/CHIP/DX910-SW-99002-r6p2-01rel0/driver/src/devicedrv/mali/__malidrv_build_info.o := arm-linux-gnueabihf-gcc -Wp,-MD,/home/intel/CHIP/DX910-SW-99002-r6p2-01rel0/driver/src/devicedrv/mali/.__malidrv_build_info.o.d  -nostdinc -isystem /usr/lib/gcc-cross/arm-linux-gnueabihf/5/include -I./arch/arm/include -Iarch/arm/include/generated/uapi -Iarch/arm/include/generated  -Iinclude -I./arch/arm/include/uapi -Iarch/arm/include/generated/uapi -I./include/uapi -Iinclude/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-dwarf2-cfi-asm -fno-ipa-sra -mabi=aapcs-linux -mno-thumb-interwork -mfpu=vfp -funwind-tables -marm -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -fno-delete-null-pointer-checks -O2 --param=allow-store-data-races=0 -Wframe-larger-than=1024 -fno-stack-protector -Wno-unused-but-set-variable -fomit-frame-pointer -fno-var-tracking-assignments -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -DCC_HAVE_ASM_GOTO -I/home/intel/CHIP/DX910-SW-99002-r6p2-01rel0/driver/src/devicedrv/mali/linux/license/gpl -DCONFIG_MALI400=1 -DCONFIG_MALI450=1 -DCONFIG_MALI470=1 -DMALI_FAKE_PLATFORM_DEVICE=1 -DCONFIG_MALI_DMA_BUF_MAP_ON_ATTACH -DCONFIG_MALI_DVFS -DMALI_PP_SCHEDULER_FORCE_NO_JOB_OVERLAP=0 -DMALI_PP_SCHEDULER_KEEP_SUB_JOB_STARTS_ALIGNED=0 -DMALI_PP_SCHEDULER_FORCE_NO_JOB_OVERLAP_BETWEEN_APPS=0 -DMALI_STATE_TRACKING=1 -DMALI_OS_MEMORY_KERNEL_BUFFER_SIZE_IN_MB=16 -DUSING_GPU_UTILIZATION=0 -DMALI_ENABLE_CPU_CYCLES=0 -DMALI_UPPER_HALF_SCHEDULING -DDEBUG -I/home/intel/CHIP/DX910-SW-99002-r6p2-01rel0/driver/src/devicedrv/mali -I/home/intel/CHIP/DX910-SW-99002-r6p2-01rel0/driver/src/devicedrv/mali/include -I/home/intel/CHIP/DX910-SW-99002-r6p2-01rel0/driver/src/devicedrv/mali/common -I/home/intel/CHIP/DX910-SW-99002-r6p2-01rel0/driver/src/devicedrv/mali/linux -I/home/intel/CHIP/DX910-SW-99002-r6p2-01rel0/driver/src/devicedrv/mali/platform -Wno-date-time -DSVN_REV_STRING=\"r6p2-01rel0\"  -DMODULE  -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(__malidrv_build_info)"  -D"KBUILD_MODNAME=KBUILD_STR(mali)" -c -o /home/intel/CHIP/DX910-SW-99002-r6p2-01rel0/driver/src/devicedrv/mali/__malidrv_build_info.o /home/intel/CHIP/DX910-SW-99002-r6p2-01rel0/driver/src/devicedrv/mali/__malidrv_build_info.c

source_/home/intel/CHIP/DX910-SW-99002-r6p2-01rel0/driver/src/devicedrv/mali/__malidrv_build_info.o := /home/intel/CHIP/DX910-SW-99002-r6p2-01rel0/driver/src/devicedrv/mali/__malidrv_build_info.c

deps_/home/intel/CHIP/DX910-SW-99002-r6p2-01rel0/driver/src/devicedrv/mali/__malidrv_build_info.o := \

/home/intel/CHIP/DX910-SW-99002-r6p2-01rel0/driver/src/devicedrv/mali/__malidrv_build_info.o: $(deps_/home/intel/CHIP/DX910-SW-99002-r6p2-01rel0/driver/src/devicedrv/mali/__malidrv_build_info.o)

$(deps_/home/intel/CHIP/DX910-SW-99002-r6p2-01rel0/driver/src/devicedrv/mali/__malidrv_build_info.o):
